name: build react app
on: push
jobs:
  build_react:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install nodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install dependencies
        run: |
            ls
            pwd
            echo "hello"
      - name: Run tests
        run: npm test 