name: build && deploy react app
on: push
jobs:
  build_react:
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: linux commands
        run: |
            ls
            pwd
            echo "hello"
      - name: Run tests
        run: npm test 
  deploy_react:
    needs: build_react
    runs-on: ubuntu-latest
    steps:
      - name: Get code from repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ..."